# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sanad < Formula
  desc "Pin and update GitHub Actions dependencies to immutable commit SHAs"
  homepage "https://github.com/MohamedElashri/sanad"
  version "0.3.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MohamedElashri/sanad/releases/download/v0.3.10/sanad_0.3.10_Darwin_x86_64.tar.gz"
      sha256 "f5547131c0191c43e06b60b55dae0b2256482be66b3da3fd26e88e7b835749c6"

      define_method(:install) do
        bin.install "sanad"
        generate_completions_from_executable(bin/"sanad", "completion", shells: [:bash, :zsh, :fish, :pwsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MohamedElashri/sanad/releases/download/v0.3.10/sanad_0.3.10_Darwin_arm64.tar.gz"
      sha256 "9747e4876e62e798e166b9981612faaeb4007d61684c93ce2471caf903007cc7"

      define_method(:install) do
        bin.install "sanad"
        generate_completions_from_executable(bin/"sanad", "completion", shells: [:bash, :zsh, :fish, :pwsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MohamedElashri/sanad/releases/download/v0.3.10/sanad_0.3.10_Linux_x86_64.tar.gz"
      sha256 "bed45605bec097d1e03130d28ba39f3b6f95947e18c506bf66d0aa2568634eea"
      define_method(:install) do
        bin.install "sanad"
        generate_completions_from_executable(bin/"sanad", "completion", shells: [:bash, :zsh, :fish, :pwsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MohamedElashri/sanad/releases/download/v0.3.10/sanad_0.3.10_Linux_arm64.tar.gz"
      sha256 "a2c981b96b0e680873fd9122e3cfacd4aee2287ced364e68ecc93fb4ab2fabbc"
      define_method(:install) do
        bin.install "sanad"
        generate_completions_from_executable(bin/"sanad", "completion", shells: [:bash, :zsh, :fish, :pwsh])
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sanad version")
  end
end
