# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sanad < Formula
  desc "Pin and update GitHub Actions dependencies to immutable commit SHAs"
  homepage "https://github.com/MohamedElashri/sanad"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MohamedElashri/sanad/releases/download/v0.1.7/sanad_0.1.7_Darwin_x86_64.tar.gz"
      sha256 "c4d3759a7c7b487c687a4f4233b6e5e52a112cb9f1cf1c3e93224031748fc193"

      define_method(:install) do
        bin.install "sanad"
        generate_completions_from_executable(bin/"sanad", "completion", shells: [:bash, :zsh, :fish, :pwsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MohamedElashri/sanad/releases/download/v0.1.7/sanad_0.1.7_Darwin_arm64.tar.gz"
      sha256 "088301a6697955ec9e675c80dbc0d0e33e7fd49c63cd60204298b881e432cfd8"

      define_method(:install) do
        bin.install "sanad"
        generate_completions_from_executable(bin/"sanad", "completion", shells: [:bash, :zsh, :fish, :pwsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MohamedElashri/sanad/releases/download/v0.1.7/sanad_0.1.7_Linux_x86_64.tar.gz"
      sha256 "1a46f4cde5b0fa4d683c6816878f0e3fca78f38ac541906fc9e83ce99845f43c"
      define_method(:install) do
        bin.install "sanad"
        generate_completions_from_executable(bin/"sanad", "completion", shells: [:bash, :zsh, :fish, :pwsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MohamedElashri/sanad/releases/download/v0.1.7/sanad_0.1.7_Linux_arm64.tar.gz"
      sha256 "f67ea3166719936d2d30e479a19787e1c0c6fe47ae5091c1605f7f34f1dabc91"
      define_method(:install) do
        bin.install "sanad"
        generate_completions_from_executable(bin/"sanad", "completion", shells: [:bash, :zsh, :fish, :pwsh])
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sanad version")
  end
end
