# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sanad < Formula
  desc "Pin and update GitHub Actions dependencies to immutable commit SHAs"
  homepage "https://github.com/MohamedElashri/sanad"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MohamedElashri/sanad/releases/download/v0.3.4/sanad_0.3.4_Darwin_x86_64.tar.gz"
      sha256 "c3fffb3c6ef31b8395f3c6b7f9ac2139cfd9941678565a1291e6fe956c57f39e"

      define_method(:install) do
        bin.install "sanad"
        generate_completions_from_executable(bin/"sanad", "completion", shells: [:bash, :zsh, :fish, :pwsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MohamedElashri/sanad/releases/download/v0.3.4/sanad_0.3.4_Darwin_arm64.tar.gz"
      sha256 "421552a8c224d4caa93312011a7041de5830ec85fee9c9d7e9a0ba2e6bfdf950"

      define_method(:install) do
        bin.install "sanad"
        generate_completions_from_executable(bin/"sanad", "completion", shells: [:bash, :zsh, :fish, :pwsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MohamedElashri/sanad/releases/download/v0.3.4/sanad_0.3.4_Linux_x86_64.tar.gz"
      sha256 "ebb8d7dd31abf2d0d34c7355aa8e446a971a666aba837c782a76444113794d88"
      define_method(:install) do
        bin.install "sanad"
        generate_completions_from_executable(bin/"sanad", "completion", shells: [:bash, :zsh, :fish, :pwsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MohamedElashri/sanad/releases/download/v0.3.4/sanad_0.3.4_Linux_arm64.tar.gz"
      sha256 "da9a26dcdadf0f7be04dbd39fcc6ba900d1464c222bdfa2ef87a062146abb89a"
      define_method(:install) do
        bin.install "sanad"
        generate_completions_from_executable(bin/"sanad", "completion", shells: [:bash, :zsh, :fish, :pwsh])
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sanad version")
  end
end
